import { drizzle } from "drizzle-orm/node-postgres";
import type pg from "pg";
import * as schema from "./schema/index.ts";

/**
 * Creates the Drizzle client for a `pg` pool. The pool owns the connections;
 * the caller creates it (with `createPool`, on the pooled `DATABASE_URL` at
 * runtime) and ends it.
 *
 * node-postgres supports interactive transactions:
 * `db.transaction(async (tx) => { ... })` runs on one connection checked out of
 * the pool and rolls back if the callback throws.
 */
export function createDb(pool: pg.Pool) {
  return drizzle({ client: pool, schema, casing: "snake_case" });
}

export type Db = ReturnType<typeof createDb>;

export {
  type AdrContentInput,
  type AdrSyncEntry,
  type AdrSyncedFile,
  type AdrSyncNotice,
  type AdrSyncNoticeCode,
  type AdrSyncProblem,
  type AdrSyncProblemReason,
  type AdrSyncReservation,
  type AdrSyncState,
  type AdrSyncSummary,
  type AdrWriter,
  MAX_ADR_FLOOR_ADVANCE,
  MAX_ADR_PATH_LENGTH,
  MAX_ADR_SYNC_ENTRIES,
  type ReserveAdrInput,
  type ReserveAdrOutcome,
  reserveAdr,
  type StoreAdrContentsOutcome,
  type SyncAdrsInput,
  type SyncAdrsOutcome,
  storeAdrContents,
  syncAdrs,
} from "./adr.ts";
export {
  type AdrDetail,
  type AdrLink,
  type AdrPage,
  type AdrReservation,
  type AdrView,
  type AdrWithChain,
  getAdr,
  type ListAdrsInput,
  listAdrs,
  MAX_ADR_CHAIN_DEPTH,
  readAdr,
  readAdrItems,
  readAdrSyncState,
  readAdrs,
  readRecentAdrs,
} from "./adr-read.ts";
export {
  createClient,
  createPool,
  describeConnectionError,
  describeFailure,
} from "./connection.ts";
export {
  allocatePlanNumber,
  COORDINATION_LOCK_NAMESPACE,
  type CoordinationContext,
  ProjectAccessLostError,
  recheckProjectAccess,
  type Transaction,
  type TryCoordinationLockResult,
  tryWithCoordinationLock,
  withAuthorizedCoordinationLock,
  withCoordinationLock,
  withCoordinationRead,
} from "./coordination.ts";
export {
  type CreationKind,
  type CreationOutcome,
  type CreationRequest,
  type CreationRows,
  createOnce,
} from "./creation.ts";
export {
  type AdrSyncChange,
  type CoverageLostReason,
  EVENT_PAYLOAD_VERSIONS,
  type EventInput,
  type EventPayloads,
  EventPayloadTooLargeError,
  type EventType,
  encodedJsonBytes,
  insertEvent,
  MAX_ADR_SYNC_EVENT_CHANGES,
  MAX_EVENT_DTO_BYTES,
  MAX_EVENT_PAYLOAD_BYTES,
} from "./event.ts";
export {
  compareFeedPositions,
  FEED_EVENT_OVERHEAD_BYTES,
  FEED_ORIGIN,
  type FeedBatch,
  type FeedPollInput,
  type FeedPosition,
  type FeedSnapshotContext,
  feedPositionOf,
  isFeedPosition,
  isIssuableFeedPosition,
  MAX_FEED_BATCH_EVENTS,
  pollEventFeed,
  readFeedHorizon,
  withFeedSnapshot,
} from "./event-feed.ts";
export { type EventFilter, listEvents, projectHasSession } from "./event-read.ts";
export {
  type CanonicalJson,
  canonicalJson,
  creationFingerprint,
  FingerprintInputTooLargeError,
  MAX_FINGERPRINT_INPUT_BYTES,
  sha256Hex,
} from "./fingerprint.ts";
export {
  type Conflict,
  claimConflictMessage,
  effectiveSessionStatusSql,
  type Forbidden,
  MAX_CONFLICT_INTENT_LENGTH,
  type NotFound,
  type ReleasedClaim,
  type SessionState,
  sessionState,
} from "./lifecycle.ts";
export {
  CLAIM_LEASE_MS,
  effectiveSessionStatus,
  HEARTBEAT_INTERVAL_MS,
  isClaimUsable,
  isSessionLive,
  LIVE_SESSION_STATUSES,
  liveSessionCondition,
  SESSION_ABANDONED_AFTER_MS,
  SESSION_STALE_AFTER_MS,
  type SessionLiveness,
} from "./liveness.ts";
export {
  type AddTaskOutcome,
  type AppendPlanLogOutcome,
  addTask,
  appendPlanLog,
  assertStorableText,
  type CreatePlanOutcome,
  type CreationFailure,
  createPlan,
  getPlan,
  type InitialPlanStatus,
  isTerminalPlanStatus,
  type ListPlansInput,
  type ListPlanTasksInput,
  listPlans,
  listPlanTasks,
  PLAN_TRANSITIONS,
  type PlanClosed,
  type PlanNotFound,
  type PlanProgress,
  type PlanView,
  type PlanWriter,
  planKey,
  planNumbers,
  readPlan,
  readPlans,
  readPlanTasks,
  resolvePlan,
  type SessionEnded,
  type SessionForbidden,
  type SessionNotFound,
  type SetPlanStatusOutcome,
  setPlanStatus,
  type TargetPlanStatus,
  type TaskView,
  UnstorableTextError,
  type UpdatePlanOutcome,
  type UsableClaim,
  updatePlan,
  usableClaim,
} from "./plan.ts";
export {
  type Actor,
  creatorColumns,
  type Principal,
  samePrincipal,
  sessionOwner,
  sessionOwnerColumns,
} from "./principal.ts";
export {
  type CreateOrReuseProjectResult,
  createOrReuseProject,
  type DbOrTransaction,
  type ProjectInput,
} from "./project.ts";
export {
  ADR_STATES,
  ADR_STATUSES,
  type Adr,
  type AdrContent,
  type AdrContentWarning,
  type AdrState,
  type AdrStatus,
  MAX_ADR_CONTENT_BYTES,
  MAX_ADR_NUMBER,
  MAX_ADR_SUPERSEDES,
  MAX_ADR_TITLE_LENGTH,
} from "./schema/adr.ts";
export {
  type AgentSession,
  CREATOR_KINDS,
  type CreatorKind,
  PLAN_STATUSES,
  type Plan,
  type PlanStatus,
  SESSION_OWNER_KINDS,
  SESSION_STATUSES,
  type SessionOwnerKind,
  type SessionStatus,
  TASK_STATUSES,
  type Task,
  type TaskStatus,
} from "./schema/coordination.ts";
export { EVENT_ACTOR_KINDS, type Event, type EventActorKind } from "./schema/event.ts";
export type { Project } from "./schema/project.ts";
export type { ProjectApiKey } from "./schema/project-api-key.ts";
export {
  SCOPE_SOURCES,
  type Scope,
  type ScopeCollectionBatch,
  type ScopeSource,
} from "./schema/scope.ts";
export {
  type DeclaredPatternInvalidReason,
  type DeclaredPatternResult,
  displayScopeValue,
  findScopeOverlaps,
  normalizeDeclaredPattern,
  normalizeTouchedPath,
  SCOPE_COMPARISON_BUDGET,
  SCOPE_PAIR_STATE_BUDGET,
  SCOPE_VALUE_MAX_BYTES,
  type ScopeComparison,
  type ScopeEntry,
  type ScopeIncompleteReason,
  ScopeMatchContext,
  type ScopeOverlap,
  type ScopeOverlapReport,
  type ScopeValue,
  type TouchedPathResult,
} from "./scope.ts";
export {
  type AddDeclaredScopeInput,
  addDeclaredScope,
  type CheckScopeOverlapInput,
  type CollectionBatchInput,
  type CollectionBatchResult,
  type CollectionInput,
  type CollectionManifestInput,
  type CollectionState,
  canonicalTouchedPaths,
  checkScopeOverlap,
  compareTouchedPaths,
  finalizeCollection,
  isScopeComplete,
  type ListScopesInput,
  listScopes,
  MAX_COLLECTION_BATCH_PATHS,
  MAX_COLLECTION_PATHS,
  MAX_DECLARED_SCOPES_PER_SESSION,
  MAX_TOUCHED_SCOPES_PER_SESSION,
  type OverlapCursor,
  type OverlapIncompleteReason,
  type OverlapScope,
  type OwnSessionInput,
  type ProjectOverlapSummary,
  type RemoveScopeInput,
  readScopes,
  recordCollectionManifest,
  removeScope,
  SCOPE_PAGE_DEFAULT_LIMIT,
  SCOPE_PAGE_MAX_LIMIT,
  type ScopeConflictReason,
  type ScopeCursor,
  type ScopeOverlapItem,
  type ScopeOverlapPage,
  type ScopeStoreFailure,
  type ScopeStoreOutcome,
  summarizeProjectOverlaps,
  touchedPathsContentHash,
  uploadCollectionBatch,
} from "./scope-store.ts";
export {
  type AttachSessionInput,
  attachSession,
  type CollectionGenerationState,
  DEFAULT_PAGE_LIMIT,
  type EndSessionInput,
  endSession,
  getSession,
  type HeartbeatResult,
  type HeartbeatSessionInput,
  heartbeatSession,
  type InvalidCursor,
  type ListSessionsInput,
  listSessionClaims,
  listSessions,
  MAX_PAGE_LIMIT,
  nextCollectionGeneration,
  type OwnedSessionRef,
  type Page,
  type PlanRef,
  pageLimit,
  readSession,
  readSessions,
  type SessionListFilter,
  type SessionMetadata,
  type SessionResult,
  type StartSessionInput,
  type StartSessionOutcome,
  startSession,
  type UpdateSessionInput,
  updateSession,
} from "./session.ts";
export {
  type LiveSessionView,
  type ProjectStatus,
  type ProjectStatusInput,
  projectStatus,
  readProjectStatus,
  type SessionView,
  type StatusSection,
  sessionViews,
} from "./status.ts";
export { type SweepOptions, type SweepResult, sweepCoordination } from "./sweep.ts";
export {
  blockTask,
  type ClaimConflict,
  claimTask,
  doneTask,
  releaseTask,
  startTask,
  type TaskActionInput,
  type TaskActionOutcome,
  type TaskActionResult,
} from "./task-claims.ts";
export { schema };
