import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, uuid } from "drizzle-orm/pg-core";
import { bigserialString, createdAt, id, timestamptz, xid8 } from "../columns.ts";
import { user } from "./auth.ts";
import { oneOf } from "./checks.ts";
import { agentSession, plan, task } from "./coordination.ts";
import { project } from "./project.ts";

// An Event records one coordination change, written in the same transaction
// as the change by `insertEvent` (src/event.ts). Plan log entries are Events
// too. Events are append-only: no code path updates or deletes them.

export const EVENT_ACTOR_KINDS = ["user", "project_key", "system"] as const;
export type EventActorKind = (typeof EVENT_ACTOR_KINDS)[number];

export const event = pgTable(
  "event",
  {
    // Server-generated, except a Plan log entry's, which is the caller's UUID
    // (for creation replay).
    id: id(),
    // Write order. UUIDs are not ordered (ADR-0005), so reads page by seq. Gaps
    // are normal (rolled-back inserts consume values) and never mean a
    // missing Event. Read as a decimal string.
    seq: bigserialString().notNull().unique("event_seq_unique"),
    // The writing transaction's id, generated by Postgres and never supplied
    // by callers. With seq it lets a reader find a safe horizon among
    // concurrently committing writers (issue #11). Read as a decimal string.
    writerXid: xid8().notNull().default(sql`pg_current_xact_id()`),
    projectId: uuid()
      .notNull()
      .references(() => project.id, { onDelete: "restrict" }),
    // A dotted type such as `task.claimed`, and the version of its payload's
    // shape. The catalog of types and payloads is in src/event.ts.
    type: text().notNull(),
    payloadVersion: integer().notNull(),
    payload: jsonb().notNull(),
    // Who did it, derived by the server from the authenticated principal.
    // `system` is the sweep. The key id has no foreign key: keys are deleted
    // on revocation, and history outlives them.
    actorKind: text({ enum: EVENT_ACTOR_KINDS }).notNull(),
    actorUserId: uuid().references(() => user.id, { onDelete: "restrict" }),
    actorKeyId: uuid(),
    // The actor's Session, when it acted through one.
    actorSessionId: uuid(),
    // The records the Event is about, separate from the actor's Session.
    planId: uuid(),
    taskId: uuid(),
    sessionId: uuid(),
    // When the change took effect, such as when a lease expired, which the
    // sweep may record later than that.
    effectiveAt: timestamptz().notNull(),
    // For a Plan log entry, the fingerprint of its original input, compared on
    // replay. Null for other Events.
    creationFingerprint: text(),
    // When the Event was written.
    createdAt: createdAt(),
  },
  (table) => [
    foreignKey({
      name: "event_actor_session_fk",
      columns: [table.actorSessionId, table.projectId],
      foreignColumns: [agentSession.id, agentSession.projectId],
    }).onDelete("restrict"),
    foreignKey({
      name: "event_plan_fk",
      columns: [table.planId, table.projectId],
      foreignColumns: [plan.id, plan.projectId],
    }).onDelete("restrict"),
    foreignKey({
      name: "event_task_fk",
      columns: [table.taskId, table.projectId],
      foreignColumns: [task.id, task.projectId],
    }).onDelete("restrict"),
    foreignKey({
      name: "event_session_fk",
      columns: [table.sessionId, table.projectId],
      foreignColumns: [agentSession.id, agentSession.projectId],
    }).onDelete("restrict"),
    index("event_project_id_seq_idx").on(table.projectId, table.seq),
    index("event_project_id_writer_xid_seq_idx").on(table.projectId, table.writerXid, table.seq),
    // Activity of a Plan, Task or Session, and what a Session did.
    index("event_plan_id_seq_idx").on(table.planId, table.seq),
    index("event_task_id_seq_idx").on(table.taskId, table.seq),
    index("event_session_id_seq_idx").on(table.sessionId, table.seq),
    index("event_actor_session_id_seq_idx").on(table.actorSessionId, table.seq),
    check("event_actor_kind_check", oneOf("actor_kind", EVENT_ACTOR_KINDS)),
    check(
      "event_actor_check",
      sql.raw(
        "(actor_kind = 'user' and actor_user_id is not null and actor_key_id is null) or " +
          "(actor_kind = 'project_key' and actor_key_id is not null and actor_user_id is null) or " +
          "(actor_kind = 'system' and actor_user_id is null and actor_key_id is null and actor_session_id is null)",
      ),
    ),
    check("event_payload_version_check", sql`${table.payloadVersion} > 0`),
    check(
      "event_creation_fingerprint_check",
      sql.raw("creation_fingerprint is null or creation_fingerprint ~ '^[0-9a-f]{64}$'"),
    ),
  ],
);

export type Event = typeof event.$inferSelect;
